terraform {
  required_version = ">= 1.15"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.66" # 6.66.0 validated this config on 2026-09-24; bump to the minor verified in Step 1
    }
  }

  # Remote state so GitHub Actions and the laptop share it. Partial config: the
  # bucket name is generated by infra/bootstrap/ and passed with
  # -backend-config="bucket=..." (TF_STATE_BUCKET repo variable in CI).
  # use_lockfile is S3-native locking (Terraform >= 1.10), same as
  # ../armed-and-dangerous/infra/versions.tf.
  backend "s3" {
    key          = "lab/terraform.tfstate"
    region       = "us-east-1"
    encrypt      = true
    use_lockfile = true
  }
}

provider "aws" {
  region = "us-east-1"
  default_tags {
    tags = { project = "redshift-redemption" }
  }
}
